# Generated by Django 3.0.5 on 2020-04-14 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=15, unique=True)),
                ('meaning_id', models.CharField(blank=True, max_length=30, null=True)),
                ('other', models.TextField(blank=True, max_length=150, null=True)),
                ('romaji', models.CharField(blank=True, max_length=60, null=True)),
                ('word_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
