# Generated by Django 3.0.5 on 2020-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20200420_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hiragana',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='katakana',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
