# Generated by Django 3.0.5 on 2020-04-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
